# Generated by Django 4.2.3 on 2023-07-19 09:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(max_length=255)),
                ("date_published", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("content", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("artwork", models.ImageField(blank=True, null=True, upload_to="")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
